# Generated by Django 6.0.1 on 2026-02-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_student_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='UGC Finance', max_length=255)),
                ('institution_email', models.EmailField(default='finance@ugc.edu.gh', max_length=254)),
                ('institution_address', models.TextField(default='P.O. Box 123, Accra, Ghana')),
                ('base_currency', models.CharField(default='GHS', max_length=10)),
                ('auto_generate_ledger', models.BooleanField(default=True)),
                ('auto_send_email_receipts', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
