# Generated by Django 6.0.1 on 2026-02-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
            ],
            options={
                'verbose_name': 'General Ledger',
                'verbose_name_plural': 'General Ledger',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoice',),
        ),
    ]
