# Generated by Django 6.0.1 on 2026-02-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
            ],
            options={
                'verbose_name': 'Financial Intelligence',
                'verbose_name_plural': 'Financial Intelligence',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.invoice',),
        ),
    ]
