# Generated by Django 6.0.1 on 2026-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_financialreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
