# Generated by Django 6.0.1 on 2026-02-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Email'), ('INVOICE', 'Invoice PDF'), ('RECEIPT', 'Receipt PDF')], default='MANUAL', max_length=20),
        ),
    ]
