# Generated by Django 6.0.1 on 2026-02-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_emaillog_attachment_name_emaillog_email_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingCenter',
            fields=[
            ],
            options={
                'verbose_name': 'Mailing Center',
                'verbose_name_plural': 'Mailing Center',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.emaillog',),
        ),
    ]
