# Generated by Django 6.0.1 on 2026-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_student_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expected_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('TUITION', 'Tuition Fees'), ('ACCOMMODATION', 'Accommodation'), ('ADMIN', 'Administrative Fees'), ('OTHER', 'Other Services')], default='TUITION', max_length=20),
        ),
    ]
