# Generated by Django 6.0.1 on 2026-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_invoice_expected_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
            ],
            options={
                'verbose_name': 'Consolidated Receipt',
                'verbose_name_plural': 'Consolidated Receipts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.payment',),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_log',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
