# Generated by Django 6.0.1 on 2026-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_receipt_payment_payment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default='Fees', max_length=50),
        ),
    ]
