# Generated by Django 6.0.1 on 2026-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='default_payment_instructions',
            field=models.TextField(blank=True, help_text='Default bank details shown on invoices (e.g. ABSA account info)', null=True),
        ),
    ]
