# Generated by Django 6.0.1 on 2026-03-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_remove_invoiceitem_service_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Update'), ('DELETE', 'Deletion'), ('AUTH', 'Authentication'), ('FINANCE', 'Financial Action')], default='UPDATE', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
