# Generated by Django 6.0.1 on 2026-03-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_activitylog_browser_activitylog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400'), ('PG', 'Post-Graduate')], default='100', max_length=10, null=True),
        ),
    ]
