[program:ugc_invoice]
directory=/root/ugc_invoice
command=/root/ugc_invoice/venv/bin/gunicorn --workers 3 --bind unix:/root/ugc_invoice/core/app.sock core.wsgi:application
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn/ugc_invoice.err.log
stdout_logfile=/var/log/gunicorn/ugc_invoice.out.log
environment=DJANGO_SETTINGS_MODULE="core.settings"