server {
    listen 80;
    listen [::]:80;
    server_name finance.ugc.edu.gh www.finance.ugc.edu.gh;
    client_max_body_size 10M;

    # Static files
    location /static/ {
        alias /root/ugc_invoice/staticfiles/;
    }

    # Media files
    location /media/ {
        alias /root/ugc_invoice/media/;
    }

    # Proxy to Django/Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/root/ugc_invoice/core/app.sock;
    }
}